### ISSUE TITLE
deploy with "bitshares-python-api-backend" together? or can work single ?

### ISSUE THREAD

**Issue by qiushaoxi** [oxarbitrage/open-explorer#1]

**Comment by grctest** [comment]
Good question, I don't believe that the backend is required unless you want to run your own servers.

It would be best practice to run your own servers, however it should just work as is with some small code changes (config).

https://github.com/oxarbitrage/open-explorer/blob/master/app/core/app.config.js#L47

```
var urls = {
    websocket: "ws://88.99.145.10:9999",
    python_backend: "http://23.94.69.140:5000",
    elasticsearch_wrapper: "http://185.208.208.184:5000",
    udf_wrapper: "http://23.94.69.140:5001"
};
```

**Comment by qiushaoxi** [comment]
is websocket bts-api?
what are elasticsearch_wrapper and udf_wrapper represent?

**Comment by grctest** [comment]
https://github.com/oxarbitrage/udf-bitshares-wrapper
https://github.com/oxarbitrage/bitshares-es-wrapper

**Comment by oxarbitrage** [comment]
thank you guys for start posting issues right away, the explorer have a lot of bugs that i hope i can get help from the community to fix.

In regards to the initial question. The explorer can run using the public wrappers in the urls at config, no need to setup your owns. However will be great if we have more public backend and wrappers.

- The UDF wrapper is for the tradingview charts used in market pages of the explorer.
- The ES wrapper is for elasticsearch database queries for account history, it is only used in the txs page of the explorer now but the plan is to use it more to make the explorer richer.
