### ISSUE TITLE
Asset view/Holders balances order of magnitude bug

### ISSUE THREAD

**Issue by clockworkgr** [oxarbitrage/open-explorer#13]
In the asset view, Top Holders list balances are 4 orders of magnitude out of place.

e.g. here:

http://open-explorer.io/#/assets/1.3.1653

compared to the correct value here:

http://open-explorer.io/#/accounts/1.2.125815 

(for the first holder)

**Comment by oxarbitrage** [comment]
this was fixed.

**Comment by oxarbitrage** [comment]
fixed long time ago, closing.
