### ISSUE TITLE
Market page - sell order price ascending order bug

### ISSUE THREAD

**Issue by grctest** [oxarbitrage/open-explorer#23]
![image](https://user-images.githubusercontent.com/15861527/37161703-51762eee-22eb-11e8-8795-a85b4d11b394.png)

12 should be below 9 when ascending sort on price.

**Comment by oxarbitrage** [comment]
this issue was fixed here https://github.com/oxarbitrage/open-explorer/commit/2a151aadfc7a82b0c4cd8eeedc750a30fc471ce0
