### ISSUE TITLE
Non account-relevant transactions displayed in account history

### ISSUE THREAD

**Issue by grctest** [oxarbitrage/open-explorer#26]
![image](https://user-images.githubusercontent.com/15861527/37246109-054a5ab6-249b-11e8-95ac-95c57c6a4e66.png)

Over time, non-relevant transactions between other parties (not involving the page's account) are displayed in real-time.
http://open-explorer.io/#/accounts/hertz-feed

Compared with:
https://wallet.bitshares.org/#/account/hertz-feed

**Comment by oxarbitrage** [comment]
this is not longer an issue as account history is not updated in real time in the explorer since a while due to this and other problems basically in page performance. 

if we decide to bring that feature up again we will handle it in a new issue.
