### ISSUE TITLE
Human readable form of orders wrong

### ISSUE THREAD

**Issue by clockworkgr** [oxarbitrage/open-explorer#32]
Example:

![image](https://user-images.githubusercontent.com/6826762/38078116-ec3584c6-3343-11e8-9f2b-4105d052c5e2.png)

I actually placed a limit order to buy 60.5621 BROWNIE.PTS for 90.84315 BTS

So the text should be:

clockwork wants 60.5621 BROWNIE.PTS for 90.84315 BTS 

and when filled  this is correct:

clockwork paid 90.84315 BTS for 60.5621 BROWNIE.PTS

**Comment by oxarbitrage** [comment]
thank you, this was fixed in this commit https://github.com/oxarbitrage/open-explorer/commit/03119dda8b6bc0b3cef188c509485756c454ac3d and is live in the 2 versions of the explorer.
