### ISSUE TITLE
Blank lines in account activity

### ISSUE THREAD

**Issue by cryptodarkforce** [oxarbitrage/open-explorer#35]
When viewing my account activity at http://open-explorer.io/#/accounts/darkf0rce, I can see a lot of blank entries which correspond to actual trades/ activity in the account. Eg. ID 1.11.174305706 is appearing as blank when it corresponds to a sell of 500 XAP for 0.0125 btc. This is making the task of compiling complete account activity quite ardous.

Please could you urgently look at this? Many thanks.

**Comment by oxarbitrage** [comment]
hi there, thanks for submitting this bug. 

there was a problem in a formatting number call i added i think last week that was giving that problem. it is now fixed.

please note not all operation types haves a human readable form at the moment so some operations may came empty in that field however the problem you pointed was related to an operation that it was already supported but buggy.

thanks again, feel free to reopen if needed.
