### ISSUE TITLE
Add Search by Transaction Id

### ISSUE THREAD

**Issue by bangzi1001** [oxarbitrage/open-explorer#37]
Exchange always ask users for Transaction ID to verify Deposit & Withdrawal and thus adding search by transaction ID function is very useful.

**Comment by oxarbitrage** [comment]
added `get_trx` call to es-wrapper as the first step needed to do this issue.

http://185.208.208.184:5000/get_trx?trx=738be2bd22e2da31d587d281ea7ee9bd02b9dbf0

exchanges can connect their applications into that url for getting operations inside a transaction.

working on adding a front end of this feature into the explorer now.

**Comment by oxarbitrage** [comment]
a transaction page was added:
http://open-explorer.io/#/txs/14022c17ea0a8a1d0221a3004dc153b7b78617c4
so if you know a trx hash you can add it to the url and get the operations inside. 

last step will be to add search form in the search page.

**Comment by oxarbitrage** [comment]
added search by trx form at http://open-explorer.io/#/search

**Comment by bangzi1001** [comment]
Just double check with Cryptofresh, the search by transaction ID function in open-explorer.io is working.

**Comment by oxarbitrage** [comment]
> Just double check with Cryptofresh, the search by transaction ID function in open-explorer.io is working.

thank you for checking that. please feel free to open new issues for anything you think the explorer can need.
