### ISSUE TITLE
Missing smartcoin/uia info within panel

### ISSUE THREAD

**Issue by grctest** [oxarbitrage/open-explorer#4]
![image](https://user-images.githubusercontent.com/15861527/35893738-4b0e911e-0ba7-11e8-9bcf-9fae66707aad.png)

![image](https://user-images.githubusercontent.com/15861527/35893758-5d03c7fe-0ba7-11e8-92b9-dbdcc45cd714.png)

**Comment by oxarbitrage** [comment]
To populate those explorer sections the backend runs a program every 24 hours. 

It seems that yesterday something was down or failed so the data was not populated. Trying to find out some more data.

That is at around 5 pm GMT. let's check after that, should be restored.

**Comment by oxarbitrage** [comment]
all this info is there now with the daily update of the database. need to make some more research about why it failed but by now it is fine.
