### ISSUE TITLE
"Click here for a CSV account exporter" displays a PHP source code instead of a CVS file

### ISSUE THREAD

**Issue by loupiote** [oxarbitrage/open-explorer#50]
When I am on an account page on bitshares-explorer.io , there is a link "Click here for a CSV account exporter".

I assume it should display or download a CSV file of the transaction history.

Instead it displays the source code of a PHP script.

Maybe the issue is that PHP is not enabled on the bitshares-explorer.io server?

**Comment by oxarbitrage** [comment]
thank you, the problem was produced by configuration when i changed to https in the explorer a few days ago.

now is working again.
