### ISSUE TITLE
Explorer not correctly displaying Collateral Bid operations

### ISSUE THREAD

**Issue by iamredbar** [oxarbitrage/open-explorer#52]
Similar to issue #51, this has to do with Collateral Bids.

View photo below, it displays the transaction type on the right side of the page, but does not make it readable on the left side of the page.

![](https://cdn.steemitimages.com/DQmZHk7paTyL8Pfw5sGWoxNgJtKg67LbV2sY39RB6rwotBP/IMG_0010.png)

**Comment by oxarbitrage** [comment]
Not all operations have the text, actually only operation types 0, 1, 2, 3, 4, 5, 6, 14, 15, 19, 22, 23, 33, 37 and now 45(bid collateral) added by your request in this commit: https://github.com/oxarbitrage/open-explorer/commit/1f6ad7a6684c433dc5c10eeda604c29335970150

You can see the operation ID and operation names here: https://open-explorer.io/#/fees

And your account will have text in the bid collateral operations: https://open-explorer.io/#/accounts/iamredbar1 but other operations outside the list i provided will be empty there as well.

I think #51 is a different problem, i am investigating.

**Comment by oxarbitrage** [comment]
Fixed for collateral bid operations. Other ops will be added in the context of issue https://github.com/oxarbitrage/open-explorer/issues/21
