### ISSUE TITLE
compass error when running grunt serve?

### ISSUE THREAD

**Issue by grctest** [oxarbitrage/open-explorer#6]
```
    Running "compass:server" (compass) task
    Warning: not found: compass Use --force to continue.
```

I tried installing the compass Ruby gem, however the error persists. What is the appropriate compass dependency I require?

I tried using `--force` and got the following other error:

```
Running "open:server" (open) task
Warning: Command failed: /root/open-explorer/node_modules/open/vendor/xdg-open "http://localhost:8000"
/root/open-explorer/node_modules/open/vendor/xdg-open: 1: /root/open-explorer/node_modules/open/vendor/xdg-open: xdg-mime: not found
xdg-open: no method available for opening 'http://localhost:8000'
 Used --force, continuing.
```

I'll try looking for appropriate node packages in the next couple days.

Cheers

**Comment by oxarbitrage** [comment]
`sudo apt install ruby-compass`

**Comment by grctest** [comment]
Thanks, that solved the compass error, however I'm still getting xdg-open errors despite repeatedly reinstalling the xdg-utils package. Any tips?

```
Running "open:server" (open) task
Warning: Command failed: /root/open-explorer/node_modules/open/vendor/xdg-open "http://localhost:8000"
xdg-open: no method available for opening 'http://localhost:8000'
 Use --force to continue.

Aborted due to warnings.
```

**Comment by oxarbitrage** [comment]
hmm, not sure about that one, it seems the machines where i installed it had that thing by default. 

check if the command is installed:

```
alfredo@alfredo-Inspiron-5559 ~/open-explorer $ xdg-open
xdg-open - opens a file or URL in the user's preferred application

Synopsis

xdg-open { file | URL }

xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
alfredo@alfredo-Inspiron-5559 ~/open-explorer $ 
```

if it is not installed maybe try:

`sudo apt-get --reinstall xdg-utils`

**Comment by grctest** [comment]
I tried reinstalling xdg-utils, the xdg-open was present. [This github issue](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1538) suggests to remove the `open` function, but I used `--force` and it works now: http://hertz.network:8000/#/dashboard

I'm going to use NGINX as a reverse web proxy & setup SSL later, looks great 👍

**Comment by oxarbitrage** [comment]
very nice. what you can do for production is `grunt serve:dist` to build a distribution in the `dist` folder and move that to your webserver location. check last part of the readme: https://github.com/oxarbitrage/open-explorer/blob/master/README.md
