### ISSUE TITLE
Asset search is case sensitive

### ISSUE THREAD

**Issue by grctest** [oxarbitrage/open-explorer#7]
![image](https://user-images.githubusercontent.com/15861527/35923662-c65f2f6a-0c18-11e8-9aa6-d21131b59cd1.png)

![image](https://user-images.githubusercontent.com/15861527/35923673-d09a1c42-0c18-11e8-9e1d-c44d6945a42c.png)

If you provide the incorrect asset case sensitivity the asset's details don't load.

**Comment by grctest** [comment]
In fact, this case-sensitivity applies to accounts, markets & assets.

**Comment by oxarbitrage** [comment]
this has been fixed:

http://open-explorer.io/#/assets/bts
=
http://open-explorer.io/#/assets/BTS

http://open-explorer.io/#/accounts/stan
=
http://open-explorer.io/#/accounts/STaN

http://open-explorer.io/#/markets/CNY/BTS
=
http://open-explorer.io/#/markets/cNy/btS

**Comment by grctest** [comment]
Great work 👍
