### ISSUE TITLE
How to run persistently?

### ISSUE THREAD

**Issue by grctest** [oxarbitrage/open-explorer#8]
I've tried running `grunt serve --force` but after about a day it will stop running, so if I'm running grunt locally and using nginx as a reverse web proxy i'll need to keep grunt running persistently, any tips? Systemd service to keep it going probably?

By running `grunt serve:dist --force` that creates static files yeah? I could just move these files into a nginx public web folder instead of running grunt persistently, yeah?

**Comment by oxarbitrage** [comment]
`grunt serve:dist` should be the best option, it will generate static files, everything minimized and optimized. i only run `grunt serve` when developing as it haves livereload. (browser tab reload when a change is detected)
